log-level: debug
muc-port: 3030
muc-link-ttl: 1440
muc-link-margin: 10
muc-find-colors: true
allow-unauthenticated: false
minio-host: localhost:9000
minio-access: replaceme
minio-secret: replacemetoo
minio-bucket: music
minio-ssl: true
sqlite-location: ./sqlite.db
